### PR TITLE
Add DELETE endpoint for a specific record in HelpRequest table

### LINKED ISSUE #36: Add `DELETE` endpoint for a specific record in HelpRequest table.
# Dependencies

This issue should be completed *after* the issue with the title "Create `HelpRequestController`..."

# Overview

In this issue, we add one more method from the example Controller used as a basis for our code; namely the method with the annotation shown below:

| Annotation | Purpose |
|-|-|
|`@DeleteMapping("")` | Delete a single record from the table; use the value passed in as a `@RequestParam` to do a lookup by id. If a matching row is not found, throw an `EntityNotFoundException`. |
       
You'll need to copy over the code for the DELETE method from the example controller, 
and then paste those into `HelpRequestController.java` and edit them to match your database table.

Then, copy over the tests that pertain to the DELETE method from the example controller,
paste those into `HelpRequestControllerTests.java` and edit them to match your database table.

# Acceptance Criteria:

- [x] In `HelpRequestController.java` there is code for an 
      endpoint `DELETE /api/HelpRequest?id=123` endpoint 
      that deletes the record if it exists, and returns 200 (ok) and 
      the text `record 123 deleted`, or returns 404 (Not Found) and
      the text `record 123 not found` if it does not.
- [x] The Swagger-UI endpoints for this endpoint is well documented
      so that any member of the team can understand how to use it.
- [x] The endpoint works as expected on localhost.
- [x] The endpoint works as expected when deployed to Dokku.
- [x] There is full test coverage (Jacoco) for the new code in 
      `HelpRequestController.java`
- [x] There is full mutation test coverage (Pitest) for new code in
      `HelpRequestController.java`

# What to do next

Do a PR, following all of the usual steps (title, description, `Closes #n` text,
dragging issue to "In Review", requesting reviewers).

Check to see if any fellow team members PRs need to be reviewed.

Then, assign yourself the next incomplete issue for your database table (`HelpRequest`)

Follow all the usual steps (assign to self, drag to "In Progress", start new branch.)

When you are done with all issues for `HelpRequest`, please give your full attention to 
helping others on your team to complete the sprint, so that the team
is ready to submit on Canvas by the deadline.

### PR DESCRIPTION
**Pull request by HououinKyouma-2036**
Added DELETE endpoint and tests.
Closes #36

### CODE REVIEW

**Comment by midnightzada** [comment]
LGTM. Will merge once requested changes for PUT endpoint PR are done or else both will be merged.

**Comment by midnightzada** [comment]
Just add "throws JsonProcessingException" in line 56 after the '(' otherwise it looks good.

**Comment by HououinKyouma-2036** [comment]
> Just add "throws JsonProcessingException" in line 56 after the '(' otherwise it looks good.

Would you please specify which ( ?

In the test file nearby line 56, I have:
@WithMockUser(roles = { "USER" })
        @Test
        public void logged_in_users_can_get_all() throws Exception {
                mockMvc.perform(get("/api/helprequest/all"))
                                .andExpect(status().is(200)); // logged
        }

In the controller file nearby line 56, I have:
@Parameter(name="solved", description="Is the request solved?", example="false") @RequestParam boolean solved) {
        
        log.info("Creating new help request by email: {}", requesterEmail);

**Comment by midnightzada** [comment]
Sorry, I meant the ')' after "boolean solved" in the controller so it should be "boolean solved) throws JsonProcessingException {"

**Comment by HououinKyouma-2036** [comment]
> Sorry, I meant the ')' after "boolean solved" in the controller so it should be "boolean solved) throws JsonProcessingException {"

:-D Thanks for telling! Just updated the changes - added JsonProcessingException {

**Pull request merged**
